### ISSUE TITLE
RNASeq input file format

### ISSUE THREAD

**Issue by mcewenrk** [InstituteCurieClinicalBioinformatics/TNBC_subtyping#1]
Hello,
do you have an example input file for the RNASeq workflow? I've been trying to run this but the following error is thrown no matter what I try

Error in read.table(inputFile, sep = "\t", row.names = TRUE, header = TRUE) :
  invalid 'row.names' specification
Calls: main -> read.table

I've been trying to work out what format is expected; is it expecting a specific column name for the gene? I'm using a tab-delimited file with genes as rows and samples as columns.

**Comment by KevinMer** [comment]
Hi @mcewenrk,

sorry to answer 4 months after your question.
Don't understand why github didn't send me a notification.

Your input is correctly formated. It was a mistake in the code. You should be able now to run the tool with your data.

Please let me know if it works.

**Comment by mcewenrk** [comment]
No problem -thank you for updating - yes it works
